# Generated by Django 4.1.5 on 2023-01-28 07:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('ph_no', models.BigIntegerField(blank=True, null=True)),
                ('relation', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_family', models.BooleanField(blank=True, null=True)),
                ('is_friend', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=300, null=True)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('hobbie', models.CharField(blank=True, max_length=300, null=True)),
                ('passion', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
