# Generated by Django 4.1.5 on 2023-01-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_password'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
