# Generated by Django 4.1.5 on 2023-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
