# Generated by Django 4.1.5 on 2023-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naem',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
