# Generated by Django 4.1.5 on 2023-01-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_naem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='naem',
            new_name='name',
        ),
    ]
